export const PRODUCTS = [
  {
    id: "kumkumadi-serum",
    name: "Pure Kumkumadi Miracle Face Serum",
    subtitle: "Instant Beauty Secret for Radiant, Glowing Glass Skin",
    category: "skincare",
    price: 1500,
    originalPrice: 1800,
    image: "images/kumkumadi_serum.jpg",
    rating: 4.9,
    reviewsCount: 148,
    badge: "Bestseller",
    size: "30 ml",
    tagline: "Ungal skin glow-ai natural-a boost panradhukku",
    description: "An authentic Ayurvedic formulation enriched with Kashmiri saffron, red sandalwood, and 28 revitalizing botanicals. Penatrates deep into epidermal layers to dissolve dark spots, stimulate natural collagen, and impart an opulent golden morning glow.",
    benefits: [
      "Visibly brightens and evens out skin tone",
      "Reduces hyperpigmentation and sun spots",
      "Promotes youthful firmness and elasticity",
      "100% pure herbal formulation without mineral oils"
    ],
    ingredients: "Kashmiri Kesar (Saffron), Chandan (Red Sandalwood), Manjistha, Licorice, Pure Sesame & Almond Infusion.",
    usage: "Dispense 3–4 drops onto cleansed palms at night. Gently massage over face and neck in upward circular strokes until fully absorbed."
  },
  {
    id: "rice-water-toner",
    name: "Korean Glass Skin Rice Water Essence",
    subtitle: "Fermented Rice & Botanical Glow Hydration",
    category: "skincare",
    price: 800,
    originalPrice: 950,
    image: "images/rice_water_toner.jpg",
    rating: 4.8,
    reviewsCount: 112,
    badge: "Trending in Korea",
    size: "150 ml",
    tagline: "Trending Korean Glass Skin Formula",
    description: "Inspired by ancient Asian glass skin rituals, this nutrient-dense fermented rice water essence floods the skin with amino acids, ferulic acid, and botanical antioxidants to tighten enlarged pores and lock in glass-like luminescence.",
    benefits: [
      "Delivers the coveted translucent Korean glass skin finish",
      "Tightens open pores and refines skin texture",
      "Balances sebum production throughout the day",
      "Calms redness, acne inflammation and irritation"
    ],
    ingredients: "Fermented Oryza Sativa (Rice) Bran Extract, Niacinamide, Sweet Almond Extract, Witch Hazel, Hyaluronic Acid.",
    usage: "After cleansing, dispense into palms or cotton pad. Pat gently onto face and neck until soaked in. Follow with Kumkumadi Serum."
  },
  {
    id: "hair-care-combo",
    name: "Super Growth Hair Oil & Shampoo Combo",
    subtitle: "Complete Herbal Root-to-Tip Strength & Growth Duo",
    category: "combos",
    price: 2300,
    originalPrice: 2800,
    image: "images/hair_care_combo.jpg",
    rating: 5.0,
    reviewsCount: 203,
    badge: "Best Value Pack",
    size: "200ml Oil + 200ml Shampoo",
    tagline: "Healthy Hair Starts Here! 100% Herbal Roots Therapy",
    description: "A synergistic duo engineered to combat hair fall, eradicate stubborn dandruff, and reactivate dormant hair follicles. Combines an intensive amla-hibiscus herbal infusion oil with an SLS-free nourishing botanical cleanser.",
    benefits: [
      "Stops aggressive hair shedding within 14 days",
      "Promotes thick baby hair growth along hairline",
      "Gentle sulfate-free wash maintains natural scalp moisture",
      "Imparts silkiness, shine, and voluminous bounce"
    ],
    ingredients: "Cold-Pressed Sesame Oil, Fresh Hibiscus Flower & Leaf Extract, Indian Amla, Bhringraj, Fenugreek, Neem, Tea Tree.",
    usage: "Warm the oil slightly and massage into scalp 2 hours before showering (or overnight). Cleanse thoroughly with the Herbal Shampoo."
  },
  {
    id: "super-growth-oil",
    name: "Super Growth Herbal Hair Elixir",
    subtitle: "Experience the Authentic Power of Nature",
    category: "haircare",
    price: 1200,
    originalPrice: 1500,
    image: "images/hair_care_combo.jpg",
    rating: 4.9,
    reviewsCount: 94,
    badge: "Customer Favorite",
    size: "200 ml",
    tagline: "Experience the Power of 21 Sacred Herbs",
    description: "Potent traditional root elixir cooked through slow herbal decoction. Rich in essential fatty acids and herbal nutrients that penetrate scalp roots directly to revitalize thin, brittle hair.",
    benefits: [
      "Accelerates hair length and follicle density",
      "Soothes itchy and dry flaky scalp",
      "Prevents premature graying with antioxidant rich amla"
    ],
    ingredients: "Pure Coconut Oil base, Bhringraj, Amla, Hibiscus, Fenugreek, Bramhi, Curry Leaves.",
    usage: "Part hair in sections and apply directly onto the scalp. Massage for 5-10 minutes with fingertips."
  },
  {
    id: "papaya-glow-soap",
    name: "Papaya & Honey Natural Glow Handmade Soap",
    subtitle: "Reveal Your Natural Glow with Botanical Enzyme Cleansing",
    category: "cleansers",
    price: 750,
    originalPrice: 900,
    image: "images/papaya_glow_soap.jpg",
    rating: 4.9,
    reviewsCount: 165,
    badge: "Top Seller",
    size: "100 g",
    tagline: "Reveal Your Natural Glow & Softness",
    description: "Hand-poured artisan soap infused with raw enzymatic papaya extract, saffron, and wild forest honey. Gently melts away dead keratin cells, revealing an instantly brighter, supple, and glowing skin tone.",
    benefits: [
      "Natural papain enzymes gently buff away dead cells",
      "Removes stubborn sun tan without drying the skin",
      "Deeply hydrates with organic raw honey",
      "Suitable for both face and body"
    ],
    ingredients: "Fresh Papaya Puree, Raw Forest Honey, Virgin Coconut Oil, Saffron Extract, Castor Oil, Glycerin.",
    usage: "Create a rich creamy lather with wet hands, massage gently over damp face and body for 60 seconds, then rinse with cool water."
  },
  {
    id: "master-whitening-pinky",
    name: "Master Whitening Pinky Face Cream",
    subtitle: "Luminous Pinkish Tone & Intense Spot Reversal",
    category: "skincare",
    price: 3800,
    originalPrice: 4500,
    image: "images/pinky_whitening_cream.jpg",
    rating: 4.9,
    reviewsCount: 88,
    badge: "Luxury Premium",
    size: "30 g",
    tagline: "AM Soul Mate Master Pinky Glow Formula",
    description: "Our crowning jewel for flawless skin. A velvety, feather-light face cream loaded with saffron stamens, lotus blossoms, and brightening botanical peptides that reverse melanin accumulation and deliver a youthful rosy petal tint.",
    benefits: [
      "Fades stubborn blemishes, acne scars, and dark circles",
      "Bestows a healthy, natural pink radiance",
      "Deep 24-hour hydration with zero greasy residue",
      "Protects against environmental pollution"
    ],
    ingredients: "Lotus Petal Extract, Kumkuma Saffron, Rose Hip Oil, Kojic Herbal Complex, Vitamin E, Shea Butter.",
    usage: "Dot sparingly across forehead, cheeks, and neck. Smooth gently outward until seamlessly melted into skin."
  },
  {
    id: "rose-face-toner",
    name: "AM Soul Mate Pure Rose Face Toner Mist",
    subtitle: "Hydro-Distilled Damask Rose Water & Hydration Elixir",
    category: "skincare",
    price: 950,
    originalPrice: 1200,
    image: "images/rose_face_toner.jpg",
    rating: 4.8,
    reviewsCount: 76,
    badge: "Pure Organic",
    size: "200 ml",
    tagline: "Pure Floral Dew for Tired, Thirsty Skin",
    description: "100% steam-distilled from freshly handpicked Kannauj and Damask rose petals. Balances pH levels, instantly revives fatigued skin, tightens pores, and preps the dermis for maximum serum absorption.",
    benefits: [
      "Instantly cools, calms, and hydrates on hot tropical days",
      "Restores natural skin acid mantle (pH 5.5)",
      "Reduces appearance of enlarged pores",
      "Doubles as a makeup setting & glow refresh spray"
    ],
    ingredients: "100% Pure Steam Distilled Damask Rose Hydrosol, Aloe Barbadensis Leaf Juice, Vegetable Glycerin.",
    usage: "Hold 8 inches away and spritz evenly across face with closed eyes. Use anytime throughout the day for an instant dewy pick-me-up."
  },
  {
    id: "charcoal-detox-soap",
    name: "AM Soul Mate Activated Charcoal Detox Soap",
    subtitle: "Pore Purification & Oil Balancing Bar",
    category: "cleansers",
    price: 700,
    originalPrice: 850,
    image: "images/charcoal_detox_soap.jpg",
    rating: 4.7,
    reviewsCount: 92,
    badge: "Deep Cleanse",
    size: "100 g",
    tagline: "Draws Out Stubborn Dirt, Toxins & Excess Sebum",
    description: "Formulated with medical-grade activated bamboo charcoal and soothing aloe vera. Acts like a microscopic vacuum for your pores, pulling out pollution, blackheads, and trapped sebum while maintaining optimal skin hydration.",
    benefits: [
      "Eliminates blackheads, whiteheads, and dead skin",
      "Deeply controls oil and stops acne outbreaks",
      "Soothes inflamed pores with organic aloe vera",
      "Leaves skin refreshed, clarified, and squeaky clean"
    ],
    ingredients: "Activated Bamboo Charcoal, Pure Aloe Vera Gel, Tea Tree Essential Oil, Olive Oil, Coconut Oil.",
    usage: "Lather between wet palms. Work over oily T-zone and blemish-prone areas for 1 minute before rinsing thoroughly."
  },
  {
    id: "beetroot-lip-balm",
    name: "Handmade Herbal Beetroot Lip Tint & Balm",
    subtitle: "Give Your Lips a Naturally Beautiful Pink Tint",
    category: "skincare",
    price: 1100,
    originalPrice: 1500,
    image: "images/beetroot_lip_balm.jpg",
    rating: 4.9,
    reviewsCount: 134,
    badge: "100% Natural",
    size: "15 g",
    tagline: "Naturally Soft, Plump, and Tinted Lips",
    description: "Handcrafted with fresh organic beetroot juice extract, sweet almond oil, and raw honeycomb wax. Reverses nicotine and sun darkening on lips while providing a gorgeous, sheer natural berry-pink blush.",
    benefits: [
      "Lightens dark, discolored and smoker-tanned lips",
      "Heals painful dry cracks and peeling skin",
      "Subtle gorgeous pink stain lasts for hours",
      "Completely chemical-free, food-grade ingredients"
    ],
    ingredients: "Organic Beetroot Extract, Pure Shea Butter, Sweet Almond Oil, Natural Beeswax, Rose Essential Oil.",
    usage: "Dab a small amount with fingertip and spread evenly over lips as needed throughout the day and before bedtime."
  },
  {
    id: "neem-coffee-scrub",
    name: "Neem, Tulsi & Coffee Natural Body Scrub",
    subtitle: "Exfoliating Herbal Body Polish for Tan & Blemish Removal",
    category: "bodycare",
    price: 1300,
    originalPrice: 1500,
    image: "images/neem_coffee_scrub.jpg",
    rating: 4.8,
    reviewsCount: 67,
    badge: "Spa Therapy",
    size: "250 g",
    tagline: "Natural Body Care from Mother Nature",
    description: "A decadent body exfoliating polish combining freshly roasted Arabica coffee grounds with antibacterial neem leaves and holy tulsi. Sloughs off dead skin cells, stimulates lymph circulation, and leaves the body satin-soft.",
    benefits: [
      "Visibly reduces body acne, back blemishes, and strawberry legs",
      "Smooths rough elbows, knees, and dark neck patches",
      "Caffeine boosts micro-circulation and firms skin",
      "Invigorating botanical herbal fragrance"
    ],
    ingredients: "Ground Arabica Coffee, Organic Neem Leaf Powder, Wild Tulsi Extract, Brown Sugar, Cold-Pressed Almond Oil.",
    usage: "Scoop a generous dollop onto damp skin during bath or shower. Scrub in firm circular motions for 3-5 minutes, focusing on rough zones, then rinse."
  },
  {
    id: "herbal-foot-care",
    name: "Herbal Cracked Heel & Foot Repair Cream",
    subtitle: "Advanced Care for Soft, Smooth, Crack-Free Feet",
    category: "bodycare",
    price: 2500,
    originalPrice: 3000,
    image: "images/herbal_foot_cream.jpg",
    rating: 4.9,
    reviewsCount: 54,
    badge: "Doctor Approved",
    size: "100 g",
    tagline: "Reduce Foot Cracks Advanced Formula",
    description: "Intense therapeutic foot balm crafted with natural beeswax, peppermint oil, and Ayurvedic repair herbs. Penetrates deeply into thick, fissured heel skin to heal painful cracks and restore baby-smooth soles.",
    benefits: [
      "Visible reduction of deep heel cracks in just 5 days",
      "Softens thick calluses and rough dry soles",
      "Antibacterial and antifungal action eliminates foot odor",
      "Invigorating cooling relief for tired, achy feet"
    ],
    ingredients: "Refined Natural Beeswax, Peppermint Oil, Sal Tree Resin (Shorea Robusta), Clove Oil, Shea Butter.",
    usage: "Wash feet with warm water and pat dry. Apply generously over heels and soles before sleeping. Wear cotton socks for overnight intensive repair."
  },
  {
    id: "milky-white-soap",
    name: "Milky White Handmade Herbal Soap",
    subtitle: "Creamy Goat Milk & Saffron Bathing Bar",
    category: "cleansers",
    price: 600,
    originalPrice: 800,
    image: "images/papaya_glow_soap.jpg",
    rating: 4.8,
    reviewsCount: 89,
    badge: "Ultra Hydrating",
    size: "100 g",
    tagline: "Pure Milky Moisture for Velvety Soft Skin",
    description: "Made with farm-fresh goat milk rich in lactic acid and essential vitamins. Gently exfoliates dead skin while providing an intense moisture blanket that prevents post-wash tightness.",
    benefits: [
      "Deeply hydrates sensitive and dry skin types",
      "Mild natural lactic acid brightens uneven patches",
      "Rich luxurious lather with gentle organic aroma"
    ],
    ingredients: "Pure Goat Milk, Saffron Extract, Coconut Oil, Castor Oil, Vitamin E.",
    usage: "Lather over wet body, leave for 1 minute to let milk enzymes work, then wash off."
  },
  {
    id: "milky-sandal-soap",
    name: "Soul Mate Milky Sandal Soap",
    subtitle: "Whitening and Pimple Out Herbal Bar",
    category: "cleansers",
    price: 750,
    originalPrice: 900,
    image: "images/papaya_glow_soap.jpg",
    rating: 4.8,
    reviewsCount: 83,
    badge: "Acne Defense",
    size: "100 g",
    tagline: "Whitening and Pimple Out Therapy",
    description: "Infused with therapeutic Mysore sandalwood oil and rich cream. Calms angry breakouts, speeds up pimple healing, and leaves an unforgettable aristocratic fragrance.",
    benefits: [
      "Clears active pimples and diminishes old redness",
      "Cools heated, sun-stressed skin instantly",
      "Gentle brightening effect without chemical bleaching"
    ],
    ingredients: "Pure Sandalwood Extract, Fresh Milk Cream, Turmeric Oil, Aloe Vera.",
    usage: "Work into lather, apply on face with extra focus on acne zones, rinse after 60 seconds."
  },
  {
    id: "complete-treatment-pack",
    name: "Complete 3-Step Skin Transformation Pack",
    subtitle: "Dull Skin? Give Your Skin the Royal Care It Deserves",
    category: "combos",
    price: 4500,
    originalPrice: 5000,
    image: "images/kumkumadi_serum.jpg",
    rating: 5.0,
    reviewsCount: 177,
    badge: "Ultimate Bundle",
    size: "3 Full Size Products",
    tagline: "Transform Your Skin in 21 Days Guaranteed",
    description: "The complete holy grail Ayurvedic ritual. Features our Deep Pore Cleanser, Luminous Glass Skin Toner, and Master Night Restorative Cream to completely rejuvenate dull, sun-damaged skin.",
    benefits: [
      "Full AM & PM comprehensive skincare regimen",
      "Maximum savings compared to buying individual items",
      "Noticeable transformation in luminosity and texture in 3 weeks"
    ],
    ingredients: "Contains Kumkumadi Face Serum, Rose Mist Toner, and Master Whitening Cream.",
    usage: "Morning: Cleanse and spray Rose Mist Toner. Evening: Apply Kumkumadi Serum followed by Night Cream."
  },
  {
    id: "soulmate-whitening-serum",
    name: "AM Soul Mate Whitening Concentrate Serum",
    subtitle: "High-Potency Herbal Drops for Stubborn Melasma",
    category: "skincare",
    price: 1800,
    originalPrice: 2200,
    image: "images/kumkumadi_serum.jpg",
    rating: 4.8,
    reviewsCount: 61,
    badge: "Intensive Care",
    size: "30 ml",
    tagline: "Soul Whitening Face Serum with Concentrated Herbs",
    description: "Concentrated herbal dropper formulation designed for persistent pigmentation, stubborn acne marks, and uneven tan lines.",
    benefits: [
      "Penetrates deep into melanin synthesis sites",
      "Non-comedogenic, oil-free absorption",
      "Boosts radiance under daily makeup"
    ],
    ingredients: "Pure Alpha Arbutin Herbal Source, Licorice Root, Saffron, Mulberry Extract.",
    usage: "Apply 2-3 drops to target areas morning and evening before face creams."
  },
  {
    id: "herbal-night-cream",
    name: "Soul Mate Herbal Beauty Fairness Night Cream",
    subtitle: "Advance Fairness and Pimple Out Overnight Rejuvenation",
    category: "skincare",
    price: 2600,
    originalPrice: 3000,
    image: "images/pinky_whitening_cream.jpg",
    rating: 4.9,
    reviewsCount: 95,
    badge: "Night Elixir",
    size: "50 g",
    tagline: "Advance Fairness and Pimple Out",
    description: "An intensive night-time botanical therapy that repairs environmental damage while you sleep. Wakes you up to ultra-soft, visibly radiant, and refreshed skin.",
    benefits: [
      "Works synergistically with skin's natural nocturnal repair cycle",
      "Diminishes dark spots and prevents new pimples",
      "Velvety luxurious consistency with quick absorption"
    ],
    ingredients: "Pure Saffron, Turmeric, Sandalwood, Almond Oil, Beeswax, Rose Water.",
    usage: "Gently massage a pea-sized amount onto face and neck after evening serum."
  },
  {
    id: "herbal-under-eye-cream",
    name: "Soul Mate Herbal Under Eye Recovery Cream",
    subtitle: "Reduce Under Eye Darkness and Puffiness",
    category: "skincare",
    price: 1800,
    originalPrice: 2000,
    image: "images/pinky_whitening_cream.jpg",
    rating: 4.7,
    reviewsCount: 52,
    badge: "Eye Care",
    size: "20 g",
    tagline: "Reduce Under Eye Darkness and Morning Bags",
    description: "Gentle under-eye botanical formula packed with cooling cucumber, caffeine, and vitamin K rich herbs to awaken tired eyes and smooth fine expression lines.",
    benefits: [
      "Fades chronic dark circles and eye bags",
      "Hydrates fragile under-eye tissue",
      "Soothes digital eye strain and burning sensations"
    ],
    ingredients: "Green Tea Extract, Cucumber Hydrosol, Almond Oil, Saffron, Aloe.",
    usage: "Gently tap with your ring finger around the orbital bone morning and night."
  },
  {
    id: "neem-green-soap",
    name: "Neem Green Herbal Beauty Soap",
    subtitle: "Pure Neem & Tulsi Antiseptic Bathing Bar",
    category: "cleansers",
    price: 750,
    originalPrice: 900,
    image: "images/papaya_glow_soap.jpg",
    rating: 4.8,
    reviewsCount: 74,
    badge: "Herbal Care",
    size: "100 g",
    tagline: "Traditional Neem Antiseptic Cleansing",
    description: "Harnesses the time-tested antibacterial powers of wild neem leaves and sacred tulsi. Clears stubborn back acne, relieves prickly heat, and neutralizes body odor.",
    benefits: [
      "Naturally shields skin against bacteria and fungi",
      "Purifies pores and controls excess sebum",
      "Gentle enough for daily whole-body bathing"
    ],
    ingredients: "Neem Leaf Extract, Tulsi, Coconut Oil, Peppermint, Camphor.",
    usage: "Lather over wet skin, massage for 1 minute, and rinse thoroughly."
  },
  {
    id: "herbal-body-lotion",
    name: "Soul Mate Herbal Body Whitening Lotion",
    subtitle: "All-Over Clean, Radiant & Fair Skin Glow",
    category: "bodycare",
    price: 2700,
    originalPrice: 3200,
    image: "images/rice_water_toner.jpg",
    rating: 4.8,
    reviewsCount: 68,
    badge: "Body Radiance",
    size: "250 ml",
    tagline: "Under Said Clean and Body Fairness",
    description: "A nourishing body milk that corrects uneven skin tone across arms, legs, back, and neck. Blended with licorice extract and shea butter to restore radiant smoothness.",
    benefits: [
      "Lightens dark knees, elbows, and bikini line",
      "Non-greasy rapid absorption formula",
      "Provides long-lasting tropical moisture"
    ],
    ingredients: "Licorice Extract, Mulberry, Shea Butter, Sweet Almond Oil, Vitamin C.",
    usage: "Smooth liberally over clean body skin daily after showering."
  },
  {
    id: "herbal-face-pack",
    name: "Soul Mate Herbal Glow Face Pack",
    subtitle: "Handmade Herbal Clay & Botanical Tightening Mask",
    category: "skincare",
    price: 750,
    originalPrice: 850,
    image: "images/neem_coffee_scrub.jpg",
    rating: 4.9,
    reviewsCount: 88,
    badge: "Ayurvedic Mask",
    size: "100 g",
    tagline: "AM Soul Mate Handmade Herbal Face Pack",
    description: "Traditional face pack powder made from sun-dried medicinal herbs, Multani Mitti (Fuller's earth), and sandalwood. Draws out deep-seated impurities while visibly tightening pores.",
    benefits: [
      "Instant party-glow radiance in 15 minutes",
      "Tightens sagging skin and shrinks open pores",
      "Absorbs excess oil and smooths rough patches"
    ],
    ingredients: "Multani Mitti, Kasturi Turmeric, Sandalwood Powder, Rose Petal Powder, Orange Peel.",
    usage: "Mix 1-2 teaspoons with AM Soul Mate Rose Mist or raw milk to form a paste. Apply on face, let dry 15 minutes, wash with cool water."
  },
  {
    id: "am-lip-cream",
    name: "AM Soul Mate Lip Glow Therapy Cream",
    subtitle: "Natural Nourishing Lip Repair Cream",
    category: "skincare",
    price: 1850,
    originalPrice: 2200,
    image: "images/beetroot_lip_balm.jpg",
    rating: 4.9,
    reviewsCount: 71,
    badge: "Lip Care",
    size: "10 g",
    tagline: "Your Lips Deserve Gentle, Natural Care",
    description: "An ultra-nourishing rich lip butter designed to repair severe dehydration, restore healthy natural rosiness, and protect against dry winds and heat.",
    benefits: [
      "Repairs chapped and sensitive lips overnight",
      "Enhances natural lip plumpness and texture",
      "Creates a smooth base under lipsticks"
    ],
    ingredients: "Wild Honey, Cocoa Butter, Vitamin E, Pomegranate Seed Oil.",
    usage: "Apply a generous coat before bed as an overnight lip sleeping mask."
  },
  {
    id: "milky-charcoal-bar",
    name: "Soul Mate Herbal Milky Charcoal Bar",
    subtitle: "Fairness and Dark Remover Daily Bath Bar",
    category: "cleansers",
    price: 300,
    originalPrice: 400,
    image: "images/charcoal_detox_soap.jpg",
    rating: 4.6,
    reviewsCount: 45,
    badge: "Budget Friendly",
    size: "75 g",
    tagline: "Fairness and Dark Remover Soap",
    description: "Everyday exfoliating charcoal bar with gentle goat milk swirl to lift away surface grime, body odors, and pollution without stripping skin oils.",
    benefits: [
      "Affordable everyday deep cleanse",
      "Gentle tan removal and fresh feeling all day"
    ],
    ingredients: "Charcoal Extract, Goat Milk, Herbal Oil Blend.",
    usage: "Lather and apply across body daily during bath."
  }
];

export const CATEGORIES = [
  { id: "all", name: "All Products", icon: "Sparkles" },
  { id: "skincare", name: "Skincare & Serums", icon: "Droplets" },
  { id: "haircare", name: "Hair Growth", icon: "Leaf" },
  { id: "cleansers", name: "Luxury Soaps", icon: "ShieldCheck" },
  { id: "bodycare", name: "Body & Spa", icon: "Heart" },
  { id: "combos", name: "Glow Combos & Kits", icon: "Gift" }
];
